services:
  
  db: 
    image: mcr.microsoft.com/mssql/server 
    environment: 
      SA_PASSWORD: "1q2w3e4r@#$" 
      ACCEPT_EULA: "Y" 
    ports: 
      - "1433:1433"
    
  
  api:
    build:
      context: .
      dockerfile: Biblioteca.Api/Dockerfile
    
    ports:
      - "8080:8080"
    
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      
    depends_on:
      - db